# Updated to match linked Supabase project
project_id = "zliugukiqtbifethrjse"

# [auth] section added to match linked Supabase project
[auth]
enabled = true
site_url = "http://localhost:3000" # Updated to match linked project
additional_redirect_urls = []      # Updated to match linked project
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

# [auth.email] section added to match linked Supabase project
[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true        # Updated to match linked project
secure_password_change = false
max_frequency = "1m0s"             # Updated to match linked project
otp_length = 6
otp_expiry = 3600

